### ISSUE TITLE
error about zju_mocap.py

### ISSUE THREAD

**Issue by yjh576** [taconite/arah-release#1]
Hi! When I was running the code, I ran into some problems in zju_mocap.py. In line  480 (https://github.com/taconite/arah-release/blob/c259ce3a87408cd278062450a14af011ad0d8fb9/im2mesh/data/zju_mocap.py#L480), I found that the dimensions of minimal_shape_v (6890x3) and self.faces (20908x3) should be the same,  but in fact they are different, leading to program errors.  I hope I can get your help!

**Comment by taconite** [comment]
Hi, yjh576

Our model uses [SMPL v1.0](https://smpl.is.tue.mpg.de/), whose mesh has 13776 faces. Judging by the information you provided it seems that you mistakenly downloaded SMPLX and extracted faces from the SMPLX model. SMPLX has a different mesh topology compared to SMPL, thus resulting in the error.

best,
Shaofei

**Comment by yjh576** [comment]
The SMPL model download requires contacting the author for download permission, right?

**Comment by taconite** [comment]
You just need to register an account on their website in order to download

**Comment by yjh576** [comment]
I can only find a download path for python 2.7 version,  I feel confusing now where to download the SMPL v1.0 for python3 version, can you plz give some detail hint for downloading this file.

**Comment by taconite** [comment]
Please check the "SMPL Setup" section of README.md of this repo.

To be specific, SMPL v1.0 for python 2.7 is the right file to download. We only need the .pkl model files, not the code. This provides you male and female models, they are called "basicmodel_m_lbs_10_207_0_v1.0.0.pkl"  and "basicModel_f_lbs_10_207_0_v1.0.0.pkl", respectively, in the downloaded .zip archive. You also need the neutral model which is available from [SMPLify](https://smplify.is.tue.mpg.de/) website. Download via the "SMPLIFY_CODE_V2.ZIP" button and inside the .zip archive, basicModel_neutral_lbs_10_207_0_v1.0.0.pkl is the neural model.

Then, you need to use [this tool](https://github.com/vchoutas/smplx/tree/master/tools) under a python2 environment (you can create such a virtual environment with conda) to remove legacy chumpy objects from each of the .pkl files.

Finally, rename and put the newly generated .pkl models into the corresponding folders, which are described in the "SMPL Setup" section of README.md of this repo. Then you can proceed to run our script `extract_smpl_parameters.py`.

**Comment by taconite** [comment]
I updated the README.md with more detailed instructions on how to get SMPL models.

**Comment by yjh576** [comment]
Great! Thanks!
