### ISSUE TITLE
Could you please provide checkpoints of zjumocap?

### ISSUE THREAD

**Issue by yijicheng** [taconite/arah-release#12]
Thanks for your excellent work!

Could you please provide checkpoints of zjumocap 313, 317, 377, 386?

I will cite this paper in my work!

**Comment by taconite** [comment]
Sorry for the delay, I have uploaded all 4-view checkpoints on ZJUMOCAP to the [model directory](https://drive.google.com/drive/folders/1ZlIvwdfHdDsdGW-6YmeDF8znvbxRgiYK?usp=sharing), please lemme know if you run into further problems. Thanks!

**Comment by yijicheng** [comment]
Thank you so much!
