### ISSUE TITLE
How can I save the rendered images when testing?

### ISSUE THREAD

**Issue by yijicheng** [taconite/arah-release#13]
Thanks for your excellent work!

How can I save the rendered images when testing? I don't find folder `vis` in the folder `out`.

**Comment by taconite** [comment]
Do you mean using `validate.py` or `train.py`? They are saved by wandb so you can view them directly on wandb website. Locally, they are saved in `out/arah-zju/${your_run}/wandb/${run_id}/files/media/images/`

**Comment by taconite** [comment]
Closed due to inactivity. Feel free to reopen it if the problem persists.
