### ISSUE TITLE
when I run test.py,error:cuda out of memory,bacth size :1,num_worker :0, single gpu;

### ISSUE THREAD

**Issue by daixiangzi** [taconite/arah-release#14]
ntimeError: CUDA out of memory. Tried to allocate 5.35 GiB (GPU 0; 31.75 GiB total capacity; 23.05 GiB already allocated; 2.25 GiB free; 28.16 GiB reserved in total by PyTorch)

**Comment by daixiangzi** [comment]
32g vram about my gpu.i think it should enough

**Comment by taconite** [comment]
Memory usage depends on image resolution and the size of the human in the image. Are you running on your own data?

If you really want to render high-res image, you can use low VRAM mode as mentioned in #11

**Comment by daixiangzi** [comment]
> Memory usage depends on image resolution and the size of the human in the image. Are you running on your own data?
> 
> If you really want to render high-res image, you can use low VRAM mode as mentioned in #11

I haved set vram=True,but still cuda out of memory; What makes me suspect is that the error does not occur during training, but during testing

**Comment by daixiangzi** [comment]
my train and test dataset of  image size is the same

**Comment by daixiangzi** [comment]
I find in  https://github.com/taconite/arah-release/blob/e28b06fd30f47ee733abe00c5e33a6eb5b33af4a/im2mesh/metaavatar_render/models/__init__.py#L200   need large vram

**Comment by daixiangzi** [comment]
https://github.com/taconite/arah-release/blob/e28b06fd30f47ee733abe00c5e33a6eb5b33af4a/im2mesh/metaavatar_render/models/__init__.py#L200

**Comment by daixiangzi** [comment]
I find:python3.9  validate.py --num-workers 4 configs/custom.yaml is ok ,but python3.9 test.py --num-workers 4 configs/custom.yaml occur cuda od memory

**Comment by daixiangzi** [comment]
when infer first image ,the code is normal, the second image cuda of out memery

**Comment by taconite** [comment]
Sorry for the late reply, I've been busy with courses and haven't got a change to look into the issue.

Not sure how you fixed it, as I updated a potential fix to the memory problem - this resolves some of my use cases, as mentioned [here](https://github.com/taconite/arah-release/issues/11#issuecomment-1326816051). Maybe try merging the latest code if your problem persists.
