### ISSUE TITLE
some issue about quantitative results of novel-view synthe Table.3

### ISSUE THREAD

**Issue by lifftel** [taconite/arah-release#20]
Thanks for your great work.
what training config do you use to compute `Table 3: Novel View Synthesis` in the paper?
I run `392_mono_4gpu.yaml` to train our model and the final results are `0.104, 27.34, and 0.926` which are less than your report results.

<img width="464" alt="1676652704562" src="https://user-images.githubusercontent.com/110417519/219714869-a6b27038-8c17-4d95-8bce-599fb9b37f82.png">
or you run 392_4gpu.yaml config? and what start_frame, end_frame, and subsampling_rate you use to compute these metrics?

**Comment by taconite** [comment]
Hi, thanks for your interest in our work!

Table 3 in the paper reports `392_4gpus.yaml`, which is the standard 4-view training setup. `mono` means monocular setup - we did not report quantitative results for the monocular setup.

For the novel view evaluation of 392, the frame range is `[0, 300)` (exclusive on the right) and the sampling rate is 30.

**Comment by taconite** [comment]
Close the issue due to inactivity.
