### ISSUE TITLE
how to get 360 novel-view image?

### ISSUE THREAD

**Issue by daixiangzi** [taconite/arah-release#21]

**Comment by daixiangzi** [comment]
I have solved this problem by add release code;

**Comment by taconite** [comment]
You can either rotate the SMPL or rotate the camera around the person. I don't have a clean code for this, but for rotating the camera, you can refer to NeuralBody's code [here](https://github.com/zju3dv/neuralbody/blob/120737bb9bf37d6c605d75b1278a6bd7a4bc0810/lib/datasets/light_stage/multi_view_perform_dataset.py#L27) which provides an example for how to interpolated between a discrete set of cameras to generate 360 free-view video.

**Comment by daixiangzi** [comment]
> You can either rotate the SMPL or rotate the camera around the person. I don't have a clean code for this, but for rotating the camera, you can refer to NeuralBody's code [here](https://github.com/zju3dv/neuralbody/blob/120737bb9bf37d6c605d75b1278a6bd7a4bc0810/lib/datasets/light_stage/multi_view_perform_dataset.py#L27) which provides an example for how to interpolated between a discrete set of cameras to generate 360 free-view video.

yes, i have solved by neralbody code
