### ISSUE TITLE
please ask some problem about result

### ISSUE THREAD

**Issue by daixiangzi** [taconite/arah-release#22]
I trained arah on my custom data; get follow result:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/24811131/222057160-bf34e36b-1fa1-4247-b7e3-27a9e2f344f7.png">

**Comment by taconite** [comment]
This is the visualization of sphere-tracing/joint-root-finding - for some rays, it might not be able to find intersecting surfaces, thus resulting in holes in visualization. For these rays, we switch back to uniform sampling on the ray, similar to neural body/animable-NeRF/etc.  You can set `gen_cano_mesh=True` [here](https://github.com/taconite/arah-release/blob/a7847143e7679ed016f64f33b33dcddff2b6e473/im2mesh/metaavatar_render/lightning_model.py#L174) to enable marching cube extraction of meshes during validation - this will cost extra time though.

**Comment by daixiangzi** [comment]
> This is the visualization of sphere-tracing/joint-root-finding - for some rays, it might not be able to find intersecting surfaces, thus resulting in holes in visualization. For these rays, we switch back to uniform sampling on the ray, similar to neural body/animable-NeRF/etc. You can set `gen_cano_mesh=True` [here](https://github.com/taconite/arah-release/blob/a7847143e7679ed016f64f33b33dcddff2b6e473/im2mesh/metaavatar_render/lightning_model.py#L174) to enable marching cube extraction of meshes during validation - this will cost extra time though.

thank you for your reply;i will try it

**Comment by daixiangzi** [comment]
I set gen_cano_mesh=True in test.py,but  model_outputs['output_normal'] is saved full black image

**Comment by daixiangzi** [comment]
> This is the visualization of sphere-tracing/joint-root-finding - for some rays, it might not be able to find intersecting surfaces, thus resulting in holes in visualization. For these rays, we switch back to uniform sampling on the ray, similar to neural body/animable-NeRF/etc. You can set `gen_cano_mesh=True` [here](https://github.com/taconite/arah-release/blob/a7847143e7679ed016f64f33b33dcddff2b6e473/im2mesh/metaavatar_render/lightning_model.py#L174) to enable marching cube extraction of meshes during validation - this will cost extra time though.

this results on test mode, not val mode

**Comment by daixiangzi** [comment]
> I set gen_cano_mesh=True in test.py,but model_outputs['output_normal'] is saved full black image

I have solved this problem by modifying img_size to myself data size
