### ISSUE TITLE
How can I get animatated mesh??

### ISSUE THREAD

**Issue by sunwonlikeyou** [taconite/arah-release#23]
There is a only code for getting canonical mesh.
Like your gifs, How can I get animated mesh??

**Comment by taconite** [comment]
You can set `gen_cano_mesh=True` [here](https://github.com/taconite/arah-release/blob/a7847143e7679ed016f64f33b33dcddff2b6e473/im2mesh/metaavatar_render/lightning_model.py#L174), the code will generate the canonical mesh and deform it via learned LBS network.

Inside the function, the canonical mesh is generated [here](https://github.com/taconite/arah-release/blob/a7847143e7679ed016f64f33b33dcddff2b6e473/im2mesh/metaavatar_render/models/__init__.py#L205)

Deformed mesh is constructed [here](https://github.com/taconite/arah-release/blob/a7847143e7679ed016f64f33b33dcddff2b6e473/im2mesh/metaavatar_render/models/__init__.py#L241) - it's the canonical mesh warped by forward LBS.

If you only need rendered normals of the meshes (as showed in the teaser gifs), the demo script already saves such images under the `vis` directory.

**Comment by sunwonlikeyou** [comment]
OMG...
It works!! Thanks a lot!!

**Comment by rexainn** [comment]
@sunwonlikeyou @taconite Hi, could you please tell me where you can find the animatated mesh? I've set `gen_cano_mesh=True` but I can't find the generated files. The only files are rendered images in the output dirs.
