### ISSUE TITLE
new problem about my custom data;

### ISSUE THREAD

**Issue by daixiangzi** [taconite/arah-release#24]
when I trained; i get checkpoint train loss is 3.34,wandb vis normal.png is normal, but I get bad normal result when I run test.py,
![img_v2_f51112ed-2dcb-4bfd-ad2f-033ed91f5aag](https://user-images.githubusercontent.com/24811131/236156058-b2f920ca-bab6-4c52-9944-0cbf07a3d0cf.jpg)

code:
model_outputs = model.model(inputs, gen_cano_mesh=True, eval=True)

**Comment by daixiangzi** [comment]
Wandb vis:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/24811131/236156440-392ae200-ee20-4ed3-8219-c1e807606b2f.png">

**Comment by taconite** [comment]
Given the current information, I cannot tell what is the problem. Maybe you can first try exporting the mesh using trimesh, and then visualize the exported mesh? You can use `points_bar` and `faces` [here](https://github.com/taconite/arah-release/blob/a7847143e7679ed016f64f33b33dcddff2b6e473/im2mesh/metaavatar_render/models/__init__.py#L226) to construct the mesh

**Comment by rexainn** [comment]
@daixiangzi @taconite Hi, I want to know where the mesh saved in the out dir? I only found rendered images, but not the cano meshes. I used offline wandb.
