### ISSUE TITLE
Out of distribution pose

### ISSUE THREAD

**Issue by zhangqianhui** [taconite/arah-release#25]
hi, thanks for sharing great research.

When I test your pretrained model of zju dataset for out of distribution pose, I don't find the directory: data/odp/CoreView_${sequence_name}/.

**Comment by taconite** [comment]
Thanks for your interest in our work :)

The [demo data](https://drive.google.com/uc?id=19D9zZIfZaKukxShsXXIia5WVsA2_7H19) contains AIST++ poses for 377 and 387. For more out of distribution poses, you can use our preprocessing script to generate them; please see [DATASET.md](https://github.com/taconite/arah-release/blob/main/DATASET.md) for details.

**Comment by zhangqianhui** [comment]
Thanks
