### ISSUE TITLE
Preprocessing code for AIST++ Dataset

### ISSUE THREAD

**Issue by jinnan-chen** [taconite/arah-release#3]
Hi, thanks for inspiring work!
Would it possible to provide preprocessing code for AIST++ dataset to convert original pkl to the npz files? Thanks!

**Comment by taconite** [comment]
Thanks for your interest in our work!
I just updated the repository with AIST++ preprocessing code. Please check DATASET.md for instructions.

**Comment by jinnan-chen** [comment]
Thanks so much!
