### ISSUE TITLE
About pretrained meta model

### ISSUE THREAD

**Issue by yf1019** [taconite/arah-release#4]
Hi shaofei,

Thanks to your great work. I'm curious about the effect of the pretrained meta model in your code: 1) meta learned skinning network on the CAPE dataset, 2) MetaAvatar SDF model. Does this really have a big influence on your result or is it just a kind of way for initialization?

Thanks a lot.

**Comment by taconite** [comment]
Hi, thanks for your interest in our work!

Overall, training without meta-learned priors should work. However, it takes much more iterations (usually 2x or more) to reach a similar quality as reported in our paper. It's also tricky to decide when to enable joint root-finding and how to schedule the near-surface sampling interval. For reproducing the exact numbers reported in the paper you probably still need the meta-learned models.

I plan to release a version that supports training without meta-learned priors next month. Though I cannot guarantee that the new version can reproduce all the numbers reported in our paper.

best,
Shaofei

**Comment by yf1019** [comment]
Got it. Thanks for your reply!
