### ISSUE TITLE
Segmentation Augmentation while Training???

### ISSUE THREAD

**Issue by sunwonlikeyou** [taconite/arah-release#7]
![image](https://user-images.githubusercontent.com/54057384/198002732-dc666bef-f619-48e3-a2f1-ad912bc6b5de.png)
![image](https://user-images.githubusercontent.com/54057384/198003273-e78fd931-a961-48ef-ba71-782ca4316afd.png)

Is there some augmentation feature in codes??? Because that looks so sharp.
When I see logfiles, there are something strange about foreground images.
If there is no problem with my datas, does it bother training?

**Comment by taconite** [comment]
No. There is no segmentation augmentation.
Your case is most likely the result of a misalignment between the 2D bounding box (from which we sample camera rays) and the actual 3D region where the person resides. This can happen if you scale up/down the image, but do not change the camera intrinsics correctly. I believe the unmodified code should not produce such results. There are too many possible pitfalls on this issue so I cannot tell the cause with only the two pictures you posted. Can you specify your modifications?

**Comment by sunwonlikeyou** [comment]
I changed img_size with ```img_size=(512, 512) if not high_res else imgsize_data``` in ./im2mesh/config.py
imgsize_data is actual image size and I'm using original intrinsic parameter.

**Comment by sunwonlikeyou** [comment]
I'm using original easymocap data. But your camera.json isn't same with my camera.json.
I know your image resoultion is 512, so that means your focal length is half of mine. But It wasn't.
This is my focal length for view 01 ```01: "K":1417.43163872 ```. And I also used this data for neural body.
and yours : ```"K": [[1074.28138836669```

**Comment by taconite** [comment]
I am not sure what "original easymocap data" means. Here are the **raw** camera 1 intrinsics from the official, unmodified ZJU-MoCap dataset, subject 377:

<img width="1179" alt="Screenshot 2022-11-06 at 12 36 29" src="https://user-images.githubusercontent.com/4970919/200168327-4ff156ae-25aa-42c2-9e1c-441f33c06642.png">

Besides, our code does not modify the original intrinsics until I call this [line](https://github.com/taconite/arah-release/blob/6ea96dd492df7151b122a64d9821ea2c6535238d/im2mesh/data/zju_mocap.py#L327). I think your camera intrinsics is somehow wrong, how did you obtain them?

**Comment by taconite** [comment]
Closed due to inactivity. Feel free to reopen it if you have further update.
